### ISSUE TITLE
Make it compatible with latest version of vscode pls thx

### ISSUE THREAD

**Issue by wingos80** [jirkavrba/vscode-subway-surfers#1]
title.

**Comment by matthewpetela** [comment]
Pretty sure it works. The command is `>This code boring ah hell`

**Comment by S3942721** [comment]
![image](https://user-images.githubusercontent.com/114715155/234157099-e5b4dfc5-06eb-4476-bb46-626079f014fa.png)
I feel like something else is meant to happen. These files are empty.

**Comment by jirkavrba** [comment]
![image](https://user-images.githubusercontent.com/14146321/234229068-e4dabbe3-6490-4fe2-90f9-3c30c2b5aaef.png)

Works fine for me on latest version of code on Linux

**Comment by wingos80** [comment]
ah nvm i was just trippin
