### ISSUE TITLE
Visual Studio Code "command not found subway-surfers.overstimulate" 

### ISSUE THREAD

**Issue by Fig12** [jirkavrba/vscode-subway-surfers#11]
Any advice?

**Comment by jirkavrba** [comment]
Try updating your visual studio code installation.

See issue https://github.com/jirkavrba/vscode-subway-surfers/issues/9 for more details :+1:

**Comment by Fig12** [comment]
Thanks chief >:)

**Comment by therealanoniem** [comment]
Update to the latest VS Code extension version.

**Comment by junaidmehmood67** [comment]
not getting activated
