### ISSUE TITLE
So Satisfying video loop

### ISSUE THREAD

**Issue by conniexu444** [jirkavrba/vscode-subway-surfers#27]
Helloooo I found a so satisfying video that I normally see under my TikTok videos with youtube ID: 

https://www.youtube.com/watch?v=zPhjxwTDdLY&t=12s

If perchance you could add this in it would be wonderful :) Thank you <3 (or any variation of a so satisfying video)

**Comment by liemeldert** [comment]
yes, this is an absolute must have!
