### ISSUE TITLE
How do I get the videos array string thingie

### ISSUE THREAD

**Issue by gurilad** [jirkavrba/vscode-subway-surfers#31]
I have a video i wanna add for myself and i can not understand how to add the custom one, i found where to add the option and saw the source code and could not understand what you did for videos, it seems to be an array of characters but yeah just trying to find a way to do that :D THANK YOU AMAZING EXTENSION BTW <3

**Comment by adxns** [comment]
those are the link of youtube video for example, a normal youtube video link might look like this `https://www.youtube.com/watch?v=dQw4w9WgXcQ` and the array of characters are the characters after `watch?v=` so in this case it will be `dQw4w9WgXcQ`

**Comment by jirkavrba** [comment]
Thanks @adxns for the explanation. I will probably add a little documentation to the custom options metadata so that it shows up while editing the value
