### ISSUE TITLE
dawwwg

### ISSUE THREAD

**Issue by hanzalah416** [jirkavrba/vscode-subway-surfers#37]
fix the extension

**Comment by Joel-Baptista** [comment]
solved

**Comment by underscorelior** [comment]
I fixed the issue in #38, we just need the author to merge the PR.

**Comment by stevenya97** [comment]
bump, are we able to get a merge soon?

**Comment by CRD716** [comment]
can we get the update pushed to marketplace, this is possibly one of the most important extensions in human history

**Comment by jirkavrba** [comment]
I pushed the latest version and set up github actions to make it automatic in the future

**Comment by stevenya97** [comment]
I don't see it updated on my end still.

**Comment by jirkavrba** [comment]
Oh I see the issue, will publish a new version

![Screenshot_20240707-071926.png](https://github.com/jirkavrba/vscode-subway-surfers/assets/14146321/dc462339-f152-4b01-ad44-7943faf212d2)

**Comment by stevenya97** [comment]
Any update?Extension was updated to 2.1.0 with no changelog and still no videos playing
