### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by Linker-123** [jirkavrba/vscode-subway-surfers#6]
In light of the human race's unfortunate experience with the industrial revolution, it is only natural to seek out advancements that not only enhance productivity but also improve the user experience. Therefore, I humbly request that the development team responsible for the "Subway Surfers" extension for "Visual Studio Code" consider implementing a feature that enables users to watch YouTube videos within the editor. This would greatly streamline the user experience and increase overall productivity. I implore the team to seriously consider this request and take positive action towards fulfilling it.

**Comment by jirkavrba** [comment]
![image](https://user-images.githubusercontent.com/14146321/235375477-9910d5b8-ffed-4c8f-9db3-208d5d5ba9c4.png)

**Comment by ferib** [comment]
Make it show feet pic instead?

**Comment by jirkavrba** [comment]
@ferib 204.226.93.19 :sunglasses:

**Comment by jirkavrba** [comment]
@Abb1x added support for Minecraft Parkour videos in https://github.com/jirkavrba/vscode-subway-surfers/pull/7 

Feel free to add your own video sources, I've tried to make it as straightforward as possible. Just add a new object with definitions and everything should be working as expected without any further modifications.

```typescript
const videoSources: Array<VideoSource> = [
    {
        label: "Subway Surfers",
        videos: ["nNGQ7kMhGuQ", "Tqne5J7XdPA", "hs7Z0JUgDeA", "iYgYfHb8gbQ"],
        width: 300,
    },
    {
        label: "Minecraft Parkour",
        videos: ["intRX7BRA90", "n_Dv4JMiwK8", "GTaXbH6iSFA", "t3SpmH9QQew"],
        width: 600,
    },
];
```
