### ISSUE TITLE
Video doesn't load, stops buffering

### ISSUE THREAD

**Issue by ishaan1013** [jirkavrba/vscode-subway-surfers#8]
Happens for both subway surfers and minecraft parkour:

![image](https://user-images.githubusercontent.com/69771365/235470018-20040022-0e17-4127-a250-b6918ef22ff4.png)

**Comment by jirkavrba** [comment]
The video hosting platform seems to be having some issues, it takes around 5 seconds for me to load the video...

**Comment by jirkavrba** [comment]
I was thinking about switching to another platform, as this extension was made in about 20 minutes originally and I didn't think it will get thousands of installations
