### ISSUE TITLE
subwaysurfers.overstimulate command not found 

### ISSUE THREAD

**Issue by dgrimes112** [jirkavrba/vscode-subway-surfers#9]
![image](https://user-images.githubusercontent.com/87717997/235507778-ff46d105-31fc-49a1-af92-3be8ebfd5e29.png)

**Comment by jirkavrba** [comment]
What version of VS Code are you using?

**Comment by dgrimes112** [comment]
1.70.1

**Comment by dgrimes112** [comment]
nvm its working now evidently you cant check for updates on the user installed version instead of the system installed, my bad ig

**Comment by jirkavrba** [comment]
Aight, glad you managed to get it working

**Comment by angelazqian** [comment]
> nvm its working now evidently you cant check for updates on the user installed version instead of the system installed, my bad ig

How did you get it working? I'm having the same problem
